### ISSUE TITLE
"Black screen" bug

### ISSUE THREAD

**Issue by ghost** [Blacksuan19/website#26]
Hi! First, great template!

However I found a anoyying issue.

After you reload the home page, the Intro text disappear, only black screen. Also skill bar animation bugged in that time.

![Screenshot_20210718-193139_Chrome](https://user-images.githubusercontent.com/87532060/126065389-904ec8c9-18ad-432f-9926-0d0dcea27110.jpg)

Thanks.

**Comment by Blacksuan19** [comment]
blame your internet

**Comment by ghost** [comment]
Are you sure? You checked it?

In my opinion, some CSS/JS are lately loaded when the site opens. Thus, the site has been opened, but not for those CSS/JS. So it waits until those fully loaded and reload the page.

**Comment by ghost** [comment]
Also how this came from my internet if it only occurs after reload?

**Comment by Blacksuan19** [comment]
just checked again, yeah it happens

**Comment by ghost** [comment]
Blame your internet too as well.

**Comment by Blacksuan19** [comment]
sure
